# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use official Node.js LTS Alpine image
FROM node:lts-alpine AS builder

# Create app directory
WORKDIR /app

# Copy package definitions
COPY package.json package-lock.json ./

# Install dependencies
RUN npm ci --ignore-scripts

# Copy source
COPY tsconfig.json ./
COPY src ./src

# Build TypeScript
RUN npm run build

# Runtime image
FROM node:lts-alpine AS runtime
WORKDIR /app

# Copy built files and production deps
COPY package.json package-lock.json ./
RUN npm ci --omit=dev --ignore-scripts
COPY --from=builder /app/dist ./dist

# Drop build tools caches
RUN rm -rf /root/.npm

# Expose default ports if needed (MCP over stdio, no port)

# Default command
ENTRYPOINT ["node", "dist/index.js"]
